
server:
  port: 1000

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus  # Exposing the Prometheus endpoint
  endpoint:
    health:
      show-details: always  # To include detailed health status
  elastic:
    metrics:
      export:
        enabled: true

spring:
  application:
    name: Full-stack
  data:
    rest:
      basePath: /api
  datasource:
    url: jdbc:postgresql://localhost:5432/testbd
    username: intranetEHC_user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
